// ─── Sovereign-ID Country Registry ──────────────────────────────────────────
// Source: Staat oder Gebiet Langform des Staatsnamens (World Peace Since Technology)
// Used for: Sovereign-ID country code picker, Guardian invite gate, etc.

export interface Country {
  de: string;   // German name
  en: string;   // English name
  iso2: string; // ISO 3166-1 alpha-2
  iso3: string; // ISO 3166-1 alpha-3
  allianceNode?: string; // Optional: mapped to Allianz-Node ID
}

export const COUNTRIES: Country[] = [
  { de: "Afghanistan",            en: "Afghanistan",               iso2: "AF", iso3: "AFG" },
  { de: "Ägypten",                en: "Egypt",                     iso2: "EG", iso3: "EGY" },
  { de: "Albanien",               en: "Albania",                   iso2: "AL", iso3: "ALB" },
  { de: "Algerien",               en: "Algeria",                   iso2: "DZ", iso3: "DZA" },
  { de: "Andorra",                en: "Andorra",                   iso2: "AD", iso3: "AND" },
  { de: "Angola",                 en: "Angola",                    iso2: "AO", iso3: "AGO" },
  { de: "Antigua und Barbuda",    en: "Antigua and Barbuda",       iso2: "AG", iso3: "ATG" },
  { de: "Äquatorialguinea",       en: "Equatorial Guinea",         iso2: "GQ", iso3: "GNQ" },
  { de: "Argentinien",            en: "Argentina",                 iso2: "AR", iso3: "ARG" },
  { de: "Armenien",               en: "Armenia",                   iso2: "AM", iso3: "ARM" },
  { de: "Aserbaidschan",          en: "Azerbaijan",                iso2: "AZ", iso3: "AZE" },
  { de: "Äthiopien",              en: "Ethiopia",                  iso2: "ET", iso3: "ETH" },
  { de: "Australien",             en: "Australia",                 iso2: "AU", iso3: "AUS" },
  { de: "Bahamas",                en: "Bahamas",                   iso2: "BS", iso3: "BHS" },
  { de: "Bahrain",                en: "Bahrain",                   iso2: "BH", iso3: "BHR" },
  { de: "Bangladesch",            en: "Bangladesh",                iso2: "BD", iso3: "BGD" },
  { de: "Barbados",               en: "Barbados",                  iso2: "BB", iso3: "BRB" },
  { de: "Belarus",                en: "Belarus",                   iso2: "BY", iso3: "BLR" },
  { de: "Belgien",                en: "Belgium",                   iso2: "BE", iso3: "BEL" },
  { de: "Belize",                 en: "Belize",                    iso2: "BZ", iso3: "BLZ" },
  { de: "Benin",                  en: "Benin",                     iso2: "BJ", iso3: "BEN" },
  { de: "Bhutan",                 en: "Bhutan",                    iso2: "BT", iso3: "BTN" },
  { de: "Bolivien",               en: "Bolivia",                   iso2: "BO", iso3: "BOL" },
  { de: "Bosnien und Herzegowina",en: "Bosnia and Herzegovina",    iso2: "BA", iso3: "BIH" },
  { de: "Botswana",               en: "Botswana",                  iso2: "BW", iso3: "BWA" },
  { de: "Brasilien",              en: "Brazil",                    iso2: "BR", iso3: "BRA" },
  { de: "Brunei",                 en: "Brunei Darussalam",         iso2: "BN", iso3: "BRN" },
  { de: "Bulgarien",              en: "Bulgaria",                  iso2: "BG", iso3: "BGR" },
  { de: "Burkina Faso",           en: "Burkina Faso",              iso2: "BF", iso3: "BFA" },
  { de: "Burundi",                en: "Burundi",                   iso2: "BI", iso3: "BDI" },
  { de: "Chile",                  en: "Chile",                     iso2: "CL", iso3: "CHL" },
  { de: "China",                  en: "China",                     iso2: "CN", iso3: "CHN" },
  { de: "Costa Rica",             en: "Costa Rica",                iso2: "CR", iso3: "CRI" },
  { de: "Dänemark",               en: "Denmark",                   iso2: "DK", iso3: "DNK" },
  { de: "Deutschland",            en: "Germany",                   iso2: "DE", iso3: "DEU", allianceNode: "ID-EU" },
  { de: "Dominica",               en: "Dominica",                  iso2: "DM", iso3: "DMA" },
  { de: "Dominikanische Republik",en: "Dominican Republic",        iso2: "DO", iso3: "DOM" },
  { de: "Dschibuti",              en: "Djibouti",                  iso2: "DJ", iso3: "DJI" },
  { de: "Ecuador",                en: "Ecuador",                   iso2: "EC", iso3: "ECU" },
  { de: "El Salvador",            en: "El Salvador",               iso2: "SV", iso3: "SLV" },
  { de: "Eritrea",                en: "Eritrea",                   iso2: "ER", iso3: "ERI" },
  { de: "Estland",                en: "Estonia",                   iso2: "EE", iso3: "EST" },
  { de: "Fidschi",                en: "Fiji",                      iso2: "FJ", iso3: "FJI" },
  { de: "Finnland",               en: "Finland",                   iso2: "FI", iso3: "FIN", allianceNode: "ID-FI" },
  { de: "Frankreich",             en: "France",                    iso2: "FR", iso3: "FRA", allianceNode: "ID-EU" },
  { de: "Gabun",                  en: "Gabon",                     iso2: "GA", iso3: "GAB" },
  { de: "Gambia",                 en: "Gambia",                    iso2: "GM", iso3: "GMB" },
  { de: "Georgien",               en: "Georgia",                   iso2: "GE", iso3: "GEO" },
  { de: "Ghana",                  en: "Ghana",                     iso2: "GH", iso3: "GHA" },
  { de: "Grenada",                en: "Grenada",                   iso2: "GD", iso3: "GRD" },
  { de: "Griechenland",           en: "Greece",                    iso2: "GR", iso3: "GRC" },
  { de: "Guatemala",              en: "Guatemala",                 iso2: "GT", iso3: "GTM" },
  { de: "Guinea",                 en: "Guinea",                    iso2: "GN", iso3: "GIN" },
  { de: "Guinea-Bissau",          en: "Guinea-Bissau",             iso2: "GW", iso3: "GNB" },
  { de: "Guyana",                 en: "Guyana",                    iso2: "GY", iso3: "GUY" },
  { de: "Haiti",                  en: "Haiti",                     iso2: "HT", iso3: "HTI" },
  { de: "Honduras",               en: "Honduras",                  iso2: "HN", iso3: "HND" },
  { de: "Indien",                 en: "India",                     iso2: "IN", iso3: "IND" },
  { de: "Indonesien",             en: "Indonesia",                 iso2: "ID", iso3: "IDN" },
  { de: "Irak",                   en: "Iraq",                      iso2: "IQ", iso3: "IRQ" },
  { de: "Iran",                   en: "Iran",                      iso2: "IR", iso3: "IRN" },
  { de: "Irland",                 en: "Ireland",                   iso2: "IE", iso3: "IRL", allianceNode: "ID-IE" },
  { de: "Island",                 en: "Iceland",                   iso2: "IS", iso3: "ISL" },
  { de: "Israel",                 en: "Israel",                    iso2: "IL", iso3: "ISR" },
  { de: "Italien",                en: "Italy",                     iso2: "IT", iso3: "ITA", allianceNode: "ID-EU" },
  { de: "Jamaika",                en: "Jamaica",                   iso2: "JM", iso3: "JAM" },
  { de: "Japan",                  en: "Japan",                     iso2: "JP", iso3: "JPN" },
  { de: "Jemen",                  en: "Yemen",                     iso2: "YE", iso3: "YEM" },
  { de: "Jordanien",              en: "Jordan",                    iso2: "JO", iso3: "JOR" },
  { de: "Kambodscha",             en: "Cambodia",                  iso2: "KH", iso3: "KHM" },
  { de: "Kamerun",                en: "Cameroon",                  iso2: "CM", iso3: "CMR" },
  { de: "Kanada",                 en: "Canada",                    iso2: "CA", iso3: "CAN" },
  { de: "Kap Verde",              en: "Cape Verde",                iso2: "CV", iso3: "CPV" },
  { de: "Kasachstan",             en: "Kazakhstan",                iso2: "KZ", iso3: "KAZ" },
  { de: "Katar",                  en: "Qatar",                     iso2: "QA", iso3: "QAT" },
  { de: "Kenia",                  en: "Kenya",                     iso2: "KE", iso3: "KEN" },
  { de: "Kirgisistan",            en: "Kyrgyzstan",                iso2: "KG", iso3: "KGZ" },
  { de: "Kolumbien",              en: "Colombia",                  iso2: "CO", iso3: "COL" },
  { de: "Komoren",                en: "Comoros",                   iso2: "KM", iso3: "COM" },
  { de: "Kongo, Demokratische Republik", en: "DR Congo",          iso2: "CD", iso3: "COD" },
  { de: "Kongo, Republik",        en: "Republic of the Congo",     iso2: "CG", iso3: "COG" },
  { de: "Korea, Nord-",           en: "North Korea",               iso2: "KP", iso3: "PRK" },
  { de: "Korea, Süd-",            en: "South Korea",               iso2: "KR", iso3: "KOR" },
  { de: "Kosovo",                 en: "Kosovo",                    iso2: "XK", iso3: "XKX" },
  { de: "Kroatien",               en: "Croatia",                   iso2: "HR", iso3: "HRV", allianceNode: "ID-EU" },
  { de: "Kuba",                   en: "Cuba",                      iso2: "CU", iso3: "CUB" },
  { de: "Kuwait",                 en: "Kuwait",                    iso2: "KW", iso3: "KWT" },
  { de: "Laos",                   en: "Laos",                      iso2: "LA", iso3: "LAO" },
  { de: "Lesotho",                en: "Lesotho",                   iso2: "LS", iso3: "LSO" },
  { de: "Lettland",               en: "Latvia",                    iso2: "LV", iso3: "LVA", allianceNode: "ID-EU" },
  { de: "Libanon",                en: "Lebanon",                   iso2: "LB", iso3: "LBN" },
  { de: "Liberia",                en: "Liberia",                   iso2: "LR", iso3: "LBR" },
  { de: "Libyen",                 en: "Libya",                     iso2: "LY", iso3: "LBY" },
  { de: "Liechtenstein",          en: "Liechtenstein",             iso2: "LI", iso3: "LIE" },
  { de: "Litauen",                en: "Lithuania",                 iso2: "LT", iso3: "LTU", allianceNode: "ID-EU" },
  { de: "Luxemburg",              en: "Luxembourg",                iso2: "LU", iso3: "LUX", allianceNode: "ID-EU" },
  { de: "Madagaskar",             en: "Madagascar",                iso2: "MG", iso3: "MDG" },
  { de: "Malawi",                 en: "Malawi",                    iso2: "MW", iso3: "MWI" },
  { de: "Malaysia",               en: "Malaysia",                  iso2: "MY", iso3: "MYS" },
  { de: "Malediven",              en: "Maldives",                  iso2: "MV", iso3: "MDV" },
  { de: "Mali",                   en: "Mali",                      iso2: "ML", iso3: "MLI" },
  { de: "Malta",                  en: "Malta",                     iso2: "MT", iso3: "MLT", allianceNode: "ID-EU" },
  { de: "Marokko",                en: "Morocco",                   iso2: "MA", iso3: "MAR" },
  { de: "Mauretanien",            en: "Mauritania",                iso2: "MR", iso3: "MRT" },
  { de: "Mauritius",              en: "Mauritius",                 iso2: "MU", iso3: "MUS" },
  { de: "Mexiko",                 en: "Mexico",                    iso2: "MX", iso3: "MEX" },
  { de: "Moldau",                 en: "Moldova",                   iso2: "MD", iso3: "MDA" },
  { de: "Monaco",                 en: "Monaco",                    iso2: "MC", iso3: "MCO" },
  { de: "Mongolei",               en: "Mongolia",                  iso2: "MN", iso3: "MNG" },
  { de: "Montenegro",             en: "Montenegro",                iso2: "ME", iso3: "MNE" },
  { de: "Mosambik",               en: "Mozambique",                iso2: "MZ", iso3: "MOZ" },
  { de: "Myanmar",                en: "Myanmar",                   iso2: "MM", iso3: "MMR" },
  { de: "Namibia",                en: "Namibia",                   iso2: "NA", iso3: "NAM" },
  { de: "Nepal",                  en: "Nepal",                     iso2: "NP", iso3: "NPL" },
  { de: "Neuseeland",             en: "New Zealand",               iso2: "NZ", iso3: "NZL" },
  { de: "Nicaragua",              en: "Nicaragua",                 iso2: "NI", iso3: "NIC" },
  { de: "Niger",                  en: "Niger",                     iso2: "NE", iso3: "NER" },
  { de: "Nigeria",                en: "Nigeria",                   iso2: "NG", iso3: "NGA" },
  { de: "Niederlande",            en: "Netherlands",               iso2: "NL", iso3: "NLD", allianceNode: "ID-EU" },
  { de: "Nordmazedonien",         en: "North Macedonia",           iso2: "MK", iso3: "MKD" },
  { de: "Norwegen",               en: "Norway",                    iso2: "NO", iso3: "NOR", allianceNode: "ID-NO" },
  { de: "Österreich",             en: "Austria",                   iso2: "AT", iso3: "AUT", allianceNode: "ID-EU" },
  { de: "Oman",                   en: "Oman",                      iso2: "OM", iso3: "OMN" },
  { de: "Pakistan",               en: "Pakistan",                  iso2: "PK", iso3: "PAK" },
  { de: "Panama",                 en: "Panama",                    iso2: "PA", iso3: "PAN" },
  { de: "Papua-Neuguinea",        en: "Papua New Guinea",          iso2: "PG", iso3: "PNG" },
  { de: "Paraguay",               en: "Paraguay",                  iso2: "PY", iso3: "PRY" },
  { de: "Peru",                   en: "Peru",                      iso2: "PE", iso3: "PER" },
  { de: "Philippinen",            en: "Philippines",               iso2: "PH", iso3: "PHL" },
  { de: "Polen",                  en: "Poland",                    iso2: "PL", iso3: "POL", allianceNode: "ID-EU" },
  { de: "Portugal",               en: "Portugal",                  iso2: "PT", iso3: "PRT", allianceNode: "ID-EU" },
  { de: "Ruanda",                 en: "Rwanda",                    iso2: "RW", iso3: "RWA" },
  { de: "Rumänien",               en: "Romania",                   iso2: "RO", iso3: "ROU", allianceNode: "ID-EU" },
  { de: "Russland",               en: "Russia",                    iso2: "RU", iso3: "RUS" },
  { de: "Sambia",                 en: "Zambia",                    iso2: "ZM", iso3: "ZMB" },
  { de: "Samoa",                  en: "Samoa",                     iso2: "WS", iso3: "WSM" },
  { de: "San Marino",             en: "San Marino",                iso2: "SM", iso3: "SMR" },
  { de: "São Tomé und Príncipe",  en: "Sao Tome and Principe",     iso2: "ST", iso3: "STP" },
  { de: "Saudi-Arabien",          en: "Saudi Arabia",              iso2: "SA", iso3: "SAU" },
  { de: "Schweden",               en: "Sweden",                    iso2: "SE", iso3: "SWE", allianceNode: "ID-SE" },
  { de: "Schweiz",                en: "Switzerland",               iso2: "CH", iso3: "CHE", allianceNode: "ID-CH" },
  { de: "Senegal",                en: "Senegal",                   iso2: "SN", iso3: "SEN" },
  { de: "Serbien",                en: "Serbia",                    iso2: "RS", iso3: "SRB" },
  { de: "Sierra Leone",           en: "Sierra Leone",              iso2: "SL", iso3: "SLE" },
  { de: "Simbabwe",               en: "Zimbabwe",                  iso2: "ZW", iso3: "ZWE" },
  { de: "Singapur",               en: "Singapore",                 iso2: "SG", iso3: "SGP" },
  { de: "Slowakei",               en: "Slovakia",                  iso2: "SK", iso3: "SVK", allianceNode: "ID-EU" },
  { de: "Slowenien",              en: "Slovenia",                  iso2: "SI", iso3: "SVN", allianceNode: "ID-EU" },
  { de: "Somalia",                en: "Somalia",                   iso2: "SO", iso3: "SOM" },
  { de: "Spanien",                en: "Spain",                     iso2: "ES", iso3: "ESP", allianceNode: "ID-EU" },
  { de: "Sri Lanka",              en: "Sri Lanka",                 iso2: "LK", iso3: "LKA" },
  { de: "Südafrika",              en: "South Africa",              iso2: "ZA", iso3: "ZAF" },
  { de: "Sudan",                  en: "Sudan",                     iso2: "SD", iso3: "SDN" },
  { de: "Südsudan",               en: "South Sudan",               iso2: "SS", iso3: "SSD" },
  { de: "Suriname",               en: "Suriname",                  iso2: "SR", iso3: "SUR" },
  { de: "Syrien",                 en: "Syria",                     iso2: "SY", iso3: "SYR" },
  { de: "Tadschikistan",          en: "Tajikistan",                iso2: "TJ", iso3: "TJK" },
  { de: "Taiwan",                 en: "Taiwan",                    iso2: "TW", iso3: "TWN" },
  { de: "Tansania",               en: "Tanzania",                  iso2: "TZ", iso3: "TZA" },
  { de: "Thailand",               en: "Thailand",                  iso2: "TH", iso3: "THA" },
  { de: "Timor-Leste",            en: "Timor-Leste",               iso2: "TL", iso3: "TLS" },
  { de: "Togo",                   en: "Togo",                      iso2: "TG", iso3: "TGO" },
  { de: "Tonga",                  en: "Tonga",                     iso2: "TO", iso3: "TON" },
  { de: "Trinidad und Tobago",    en: "Trinidad and Tobago",       iso2: "TT", iso3: "TTO" },
  { de: "Tschad",                 en: "Chad",                      iso2: "TD", iso3: "TCD" },
  { de: "Tschechien",             en: "Czech Republic",            iso2: "CZ", iso3: "CZE", allianceNode: "ID-EU" },
  { de: "Tunesien",               en: "Tunisia",                   iso2: "TN", iso3: "TUN" },
  { de: "Türkei",                 en: "Turkey",                    iso2: "TR", iso3: "TUR" },
  { de: "Turkmenistan",           en: "Turkmenistan",              iso2: "TM", iso3: "TKM" },
  { de: "Uganda",                 en: "Uganda",                    iso2: "UG", iso3: "UGA" },
  { de: "Ukraine",                en: "Ukraine",                   iso2: "UA", iso3: "UKR" },
  { de: "Ungarn",                 en: "Hungary",                   iso2: "HU", iso3: "HUN", allianceNode: "ID-EU" },
  { de: "Uruguay",                en: "Uruguay",                   iso2: "UY", iso3: "URY" },
  { de: "USA",                    en: "United States",             iso2: "US", iso3: "USA", allianceNode: "ID-US" },
  { de: "Usbekistan",             en: "Uzbekistan",                iso2: "UZ", iso3: "UZB" },
  { de: "Vatikanstadt",           en: "Vatican City",              iso2: "VA", iso3: "VAT" },
  { de: "Venezuela",              en: "Venezuela",                 iso2: "VE", iso3: "VEN" },
  { de: "Vereinigte Arabische Emirate", en: "United Arab Emirates",iso2: "AE", iso3: "ARE" },
  { de: "Vereinigtes Königreich", en: "United Kingdom",           iso2: "GB", iso3: "GBR" },
  { de: "Vietnam",                en: "Vietnam",                   iso2: "VN", iso3: "VNM" },
  { de: "Weißrussland",           en: "Belarus",                   iso2: "BY", iso3: "BLR" },
  { de: "Zentralafrikanische Republik", en: "Central African Republic", iso2: "CF", iso3: "CAF" },
  { de: "Zypern",                 en: "Cyprus",                    iso2: "CY", iso3: "CYP", allianceNode: "ID-EU" },
];

// Helper: sorted alphabetically by German name
export const COUNTRIES_SORTED = [...COUNTRIES].sort((a, b) => a.de.localeCompare(b.de, "de"));

// Helper: get country code prefix for Sovereign-ID
export function getCountryPrefix(iso2: string): string {
  return iso2.toUpperCase();
}

// Helper: alliance node countries only
export const ALLIANCE_COUNTRIES = COUNTRIES.filter((c) => c.allianceNode);
