[build]
  command   = "npx prisma generate && npm run build"
  publish   = ".next"

[build.environment]
  NODE_VERSION        = "20"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_PRIVATE_STANDALONE = "true"
